In [1]:
import pandas as pd
print("Pandas Imported")



Pandas Imported


In [ ]:
num = int(input("Enter a Number"))
count = 0
for i in range(num):
  if num% i== 0:
    count += 1

if count ==2:
  print("Prime Number")
else:
  print("Not a Prime Number")

In [ ]:
#Creating Series
import pandas as pd
data = [1,2,3,4,5]
i= ['a','b','e','c','d']
s= pd.Series(data, index = i)
s['a']= 30
s['f']= 6
s= s.drop('a')
print(s)

In [ ]:
data = [1,2,3,4]
s2 = pd.Series({'x':100, 'y':200, 'z':300})
print(s2)

x    100
y    200
z    300
dtype: int64


In [ ]:
sid = [101,102,103,104,105]
marks = [78,85,92,67,88]
s = pd.Series(marks, index = sid)
print(s[103])
s[104] = 75
s= s.drop(102)
s[106] = 90
print(s)

92
101    78
103    92
104    75
105    88
106    90
dtype: int64


In [ ]:
s= pd.Series(
    [25000, 28000, 32000, None, 35000, 30000, None, 42000, 45000, 48000],
    index=["01-Aug", "02-Aug", "03-Aug", "04-Aug", "05-Aug", "06-Aug", "07-Aug", "08-Aug", "09-Aug", "10-Aug"])
print(s.head(5))
print(s.tail(3))
print(s.isna())
print(s.isna().sum())
print(s.fillna(s.mean()))
s["03-Aug"]= 34000
print(s>35000)
s.drop("04-Aug")
s["11-Aug"]= 50000
print(s.mean())
print(s.sum())
print(s.max())
print(s.min())

In [ ]:
s = pd.Series(
    [120000, 135000, None, 150000, 165000, None, 180000, 195000, 210000, 225000],
    index=["January", "February", "March", "April", "May", "June", "July", "August", "September", "October"])
print(s.head(5))
print(s.tail(3))
print(s[["January", "March", "May"]])
print(s>170000)
print(s.isna())
print(s.isna().sum())
print(s.fillna(s.mean()))
s["April"]= 155000
s= s.drop("February")
s["November"]= 240000
print(s.sum)
print(s.mean())
print(s.max())
print(s.min())

In [ ]:
s= pd.Series(
    [5000, 7000, 6000, 9000, 8000],
    index=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"])
print(s)
s.iloc[0:3]
s.iloc[0]
s.loc['Monday']
#Aggregation Techniques
s.mean()
s.median()
s.count()
s.min()
s.max()
s.std()
s.sum()

In [ ]:
data = {
    "Name" : ["Ravi","Priya","Arun", "Sneha", "Kiran", "Anjali", "Vikram", "Meena"],
    "Age" : [22, 24, None, 25, None, 26, 20, 27],
    "City" : ["Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Mumbai", None, "Bangalore", "Mumbai"],
    "Salary" : [30000, 40000, 25000, 50000, 35000, 45000, None, 55000]
}
i = [101,102,103,104,105,106,107,108]
df= pd.DataFrame(data, index = i)
df.loc[101] #loc is used to pass the index position as an argument
df.iloc[0] #iloc is used to pass the position as a list(starting from 0) as an argument
e = df["Age"] > 21 #returns a boolean value regd the argument
print(e)
d = df[df["Age"] > 21] #returns only the data that satisfied the condition
a= df[df["Salary"] > 40000]
print(a)
print(df.head())
print(df.tail())
print(df.count())
df.shape
df.index
df.values
b= df[(df["City"] == "Hyderabad") & (df["Age"] > 23)]
print(b)
#df.dropna(axis=1) #remove entire columns containing missing values
#df.dropna(axis=0) #removes entire rows containing missing values
#df.dropna(how='all') #remove only completely empty rows
#df.dropna(inplace=True) #to modify the original DataFrame
#df.fillna(0) #to fill empty Frames with the value 0
df.fillna({'Age' : 0, 'City' : 'Unknown'}) #to fill empty frames with the specified values for the respective column
df['Age'] = df['Age'].fillna(df['Age'].mean()) #to fill missing numerical value frames with mean

101     True
102     True
103    False
104     True
105    False
106     True
107    False
108     True
Name: Age, dtype: bool
       Name   Age       City   Salary
104   Sneha  25.0  Hyderabad  50000.0
106  Anjali  26.0       None  45000.0
108   Meena  27.0     Mumbai  55000.0
      Name   Age       City   Salary
101   Ravi  22.0  Hyderabad  30000.0
102  Priya  24.0    Chennai  40000.0
103   Arun   NaN  Bangalore  25000.0
104  Sneha  25.0  Hyderabad  50000.0
105  Kiran   NaN     Mumbai  35000.0
       Name   Age       City   Salary
104   Sneha  25.0  Hyderabad  50000.0
105   Kiran   NaN     Mumbai  35000.0
106  Anjali  26.0       None  45000.0
107  Vikram  20.0  Bangalore      NaN
108   Meena  27.0     Mumbai  55000.0
Name      8
Age       6
City      7
Salary    7
dtype: int64
      Name   Age       City   Salary
104  Sneha  25.0  Hyderabad  50000.0


In [ ]:
s = pd.Series(
    [1, 2, 3, 4],
    name= 'Numbers')
s2 = pd.Series([9, 6, 5, 8])
s3= pd.Series([12, 13, 14, 15])
d= {
    "name" : s,
    "age" : s2,
    "marks" : s3}
df = pd.DataFrame(d) # Converting dict into a Data Frame
print(df)
s.columns = ['Digits'] #To rename a column in a Series
df.rename(columns={'age' : 'Alpha', 'marks' : 'Beta'}, inplace=True) #To rename an exisitng column in a DataFrame
print(df)
print(df.head())
print(df.tail())
print(df.count())
print(df.shape)
print(df.info()) #used to display the structural information about the df
print(df.describe()) #used to display the statistical information about the df
print(df[['Alpha','name']]) #to display multiple columns
bet= df['Beta']
print(bet)


   name  age  marks
0     1    9     12
1     2    6     13
2     3    5     14
3     4    8     15
   name  Alpha  Beta
0     1      9    12
1     2      6    13
2     3      5    14
3     4      8    15
   name  Alpha  Beta
0     1      9    12
1     2      6    13
2     3      5    14
3     4      8    15
   name  Alpha  Beta
0     1      9    12
1     2      6    13
2     3      5    14
3     4      8    15
name     4
Alpha    4
Beta     4
dtype: int64
(4, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      int64
 1   Alpha   4 non-null      int64
 2   Beta    4 non-null      int64
dtypes: int64(3)
memory usage: 228.0 bytes
0    12
1    13
2    14
3    15
Name: Beta, dtype: int64


In [ ]:
emp_details = {
    'EmpID': [101,102,103,104,105],
    'City': ['Hyderabad','Chennai','Bangalore',None,'Hyderabad'],
    'Experience': [None,4,3,5,2],
    'Age': [25,30,None,35,25]
}
data = {
    "EmpID" : [101,102,103,104,105,106,107,108],
    "Name" : ["Ravi","Priya","Arun", "Sneha", "Kiran", "Anjali", "Vikram", "Meena"],
    "Age" : [22, 24, None, 25, None, 26, 20, 27],
    "City" : ["Hyderabad", "Chennai", "Bangalore", "Hyderabad", "Mumbai", None, "Bangalore", "Mumbai"],
    "Salary" : [30000, 40000, 25000, 50000, 35000, 45000, None, 55000]
}
df1= pd.DataFrame(data)
df = pd.DataFrame(emp_details)
print(df)
df.isna()
df.isna().sum()
df.fillna({'City' : 'Unknown', 'Experience': 0, 'Age': df['Age'].mean()}, inplace=True)
#df.rename(columns={'EmpID':'Employee_ID'}, inplace=True)
df['Salary']= [35000,23000,25000,46000,78000]
df['Age'] = df['Age'] + 1
df['Bonus'] = df['Salary'] / 10
df.drop('Bonus', axis= 1, inplace=True) #to drop a SINGLE column
df.drop(0,axis=0,inplace=True) #to drop a single row; [0,1] to drop MULTIPLE
#df.drop(columns=['Salary'],inplace=True) #to drop MULTIPLE columns
#df.loc[len(df)]= [109, 'Seattle', 7, 40, 57000]
print(df.groupby('City')['Age'].mean()) #groups by city w the mean age.
print(df.groupby('City')['Age'].agg(['mean', 'max','min'])) #used .agg to perform multiple aggregations on a SINGLE coulmn
print(df.groupby('City').agg({'Age' : ['mean','max'], 'Salary' : ['sum', 'count']})) #can use .agg to perform multiple aggregations on MULTIPLE columns
print(df)
merged = pd.merge( df, df1, on = 'EmpID', how = 'left') #used to merge two DF's with left, right, inner and outer forms
print(merged)

df.dropna(axis=0)
df.dropna(axis=1)
df.dropna(how = 'all')
df.dropna(inplace=True)

   EmpID       City  Experience   Age
0    101  Hyderabad         NaN  25.0
1    102    Chennai         4.0  30.0
2    103  Bangalore         3.0   NaN
3    104       None         5.0  35.0
4    105  Hyderabad         2.0  25.0
City
Bangalore    29.75
Chennai      31.00
Hyderabad    26.00
Unknown      36.00
Name: Age, dtype: float64
            mean    max    min
City                          
Bangalore  29.75  29.75  29.75
Chennai    31.00  31.00  31.00
Hyderabad  26.00  26.00  26.00
Unknown    36.00  36.00  36.00
             Age        Salary      
            mean    max    sum count
City                                
Bangalore  29.75  29.75  25000     1
Chennai    31.00  31.00  23000     1
Hyderabad  26.00  26.00  78000     1
Unknown    36.00  36.00  46000     1
   EmpID       City  Experience    Age  Salary
1    102    Chennai         4.0  31.00   23000
2    103  Bangalore         3.0  29.75   25000
3    104    Unknown         5.0  36.00   46000
4    105  Hyderabad         2.0 

In [ ]:
import pandas as pd
data = {
"EmpID" : [101,102,103,104,105,106,107,108,109,110,110],
"Name": ["Ravi", "PRIYA", "Arun", "sneha", "Kiran", "ANJALI", "Vikram","meena", "RAHUL", "Sneha", "Sneha"],
"City": ["Hyderabad", "Hyderabad", "CHENNAI", "Chennai", "Bangalore", "BANGALORE", "Mumbai", "mumbai", "Delhi", "Hyderabad", "Hyderabad"],
"Salary": [30000, 40000, 3500, 4500, 32000, 50000, 38000, 42000, 36000, 45000, 45000]
}
df = pd.DataFrame(data)
print(df)
df.duplicated() #to find the duplicate values in a DataFrame
#df.duplicated().sum() #used to find the no. of duplicate items
duplicates = df[df.duplicated()]
originals = df[df.duplicated(keep= False)] #used to store only the original values
total = duplicates["Salary"].sum() #to calc statistical info on the duplicate values
print(total)
#df['EmpID'].duplicated() #to display duplicates in a single column
df.drop_duplicates() #to remove duplicates in the DataFrame, keeping the first one
#df.drop_duplicates(keep= "last") #to remove the duplicates in the DataFrame from first occurence and to keep only the last one
#df = df.drop_duplicates( subset = ["EmpID"], keep = "first")
#df["City"] = df["City"].str.title() #to convert the data where the first letter is capitalized and the rest is lowered in case
print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   sneha    Chennai    4500
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000
45000
    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   sneha    Chennai    4500
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000


In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")
print(df)
df1= pd.read_excel('/content/Sample - Superstore.csv.xlsx', sheet_name = 'Sample - Superstore')
print(df1)
df.shape()
df.head(10)
df.tail(8)
df

In [ ]:
data = {
  "TransactionID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1010, 1011],
  "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran", "Anjali", "Vikram", "Meena", "Rahul", "Sneha", "Sneha", "Kiran"],
  "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse", "Keyboard", "Monitor", "Laptop", "Mobile", "Headphones", "Headphones", "Mouse"],
  "Amount": [55000, 25000, 30000, 5000, 1500, 2500, 18000, 55000, 22000, 5000, 5000, 1500]}

df_sales = pd.DataFrame(data)
print(df_sales)
duplicates = df_sales[df_sales.duplicated()]
print(duplicates)
coun = duplicates["TransactionID"].sum()
print(df_sales[df_sales.duplicated(keep = False)])
print(duplicates['TransactionID']) #4
df_sales['Customer'] = df_sales['Customer'].str.lower()
df_sales['Customer'] = df_sales['Customer'].str.strip().str.title()
#df_sales['Customer'] = df_sales['Customer'].str.strip()
df_sales['Product'] = df_sales['Product'].str.strip().str.lower()
#df_sales['Product'] = df_sales['Product'].str.strip().str.title()
#df_sales['Customer'], df_sales['Product'] = df_sales['Customer'].str.strip().str.title(), df_sales['Product'].str.strip().str.title() #6
#df_sales['Product'] = df_sales['Product'] == "laptop".str.lower() #7
print(df_sales[df_sales['Customer'] == "Sneha"]) #8

df_sales['Customer'], df_sales['Product'] = df_sales['Customer'].str.strip().str.title(), df_sales['Product'].str.strip().str.title() #10
print(df_sales)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500
    TransactionID Customer     Product  Amount
10           1010    Sneha  Headphones    5000
    TransactionID Customer     Product  Amount
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
10    1010
Name: TransactionID, dtype: int64
    TransactionID Customer     Product  Amount
3            1004    Sneha  headphones    5000
9            10

In [ ]:
data = {
  "VisitID": [501,502,503,504,505,506,507,508,509,510,510,511],
  "Patient": ["Rahul","Anita","Suresh","Priya","Kiran","Anjali","Ravi","Meena","Arun","Priya","Priya","Kiran"],
  "Department": ["Cardiology","Neurology","Orthopedic","General","Dental","Cardiology","Neurology","General","Dental","Cardiology","Cardiology","Dental"],
  "BillAmount": [5000,7500,4500,2000,1500,6000,7000,2500,1800,6000,6000,1500]}
df_patient = pd.DataFrame(data)

print(df_patient)
duplicates = df_patient[df_patient.duplicated()] #1
print(duplicates)
duplicate_count = df_patient.duplicated().sum() #2
print(f"Number of duplicate records: {duplicate_count}")

all_duplicates = df_patient[df_patient.duplicated(keep=False)] #3
print(all_duplicates)

duplicate_bill_total = df_patient[df_patient.duplicated()]['BillAmount'].sum() #4
print(f"Total BillAmount of duplicates: {duplicate_bill_total}")

visit_id_duplicates = df_patient[df_patient.duplicated(subset=['VisitID'], keep=False)] #5
print(visit_id_duplicates)

returning_patients = df_patient[df_patient.duplicated(subset=['Patient'], keep=False)] #6
print(returning_patients)

df_no_full_dupes = df_patient.drop_duplicates() #7
df_unique_visits = df_patient.drop_duplicates(subset=['VisitID']) #8
df_unique_patient_dept = df_patient.drop_duplicates(subset=['Patient', 'Department']) #9
df_cleaned = df_patient.drop_duplicates(subset=['VisitID']).copy() #10
df_cleaned.reset_index(drop=True, inplace=True)

print("Final Cleaned Dataset:")
print(df_cleaned)
#df["Date"]= pd.to_datetime(df["Date"]) #to convert the column to Date and Time data type

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500
    VisitID Patient  Department  BillAmount
10      510   Priya  Cardiology        6000
Number of duplicate records: 1
    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
Total BillAmount of duplicates: 6000
    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
    Visi

In [ ]:
import pandas as pd
data = {
    "Date": [
        "2025-01-01",
        "2025-01-02",
        "2025-01-03",
        "2025-01-04",
        "2025-01-05"
    ],
    "Sales": [5000, 6500, 4200, 7000, 5500]}
df = pd.DataFrame(data)
print(df)
print(df.dtypes)
df["Date"] = pd.to_datetime(df["Date"])
print(df.dtypes)
#dates = pd.date_range(start="2025-01-01", end="2025-01-10") #to generate number from Jan 1 to 10
#dates = pd.date_range(start="2025-01-01",periods=10) #to generate a fixed number of values from Jan 1
dates = pd.date_range(start="2025-01-01",periods=10,freq="D") #to generate days on the frequency 'D' which is DAY, 'sec'-seconds, 'MS'-Month Start, 'ME'-Month End, 'YS'-Year Start, 'YE'- Year End, 'H'-Hours, 'min'-Minutes
print(dates)


         Date  Sales
0  2025-01-01   5000
1  2025-01-02   6500
2  2025-01-03   4200
3  2025-01-04   7000
4  2025-01-05   5500
Date     object
Sales     int64
dtype: object
Date     datetime64[ns]
Sales             int64
dtype: object
DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')


In [ ]:
import pandas as pd
import numpy as np
dates= pd.date_range(start="2025-01-01",periods= 30, freq="MS")
sales= np.random.randint(2000,10000, size=30)
df= pd.DataFrame({"Date": dates, "Sales": sales})
print(df)
df["Date"]= pd.to_datetime(df["Date"])
#df["Date"].dt.year #to collect frames which have the specified year
#df.groupby(df["Date"].dt.year)["Sales"].sum() #to perform a certain statistic upon every year
#print(df.groupby(df["Date"].dt.year)["Sales"].mean())
#print(df.groupby(df["Date"].dt.year)["Sales"].max())
#print(df['Date'].dt.month)
df["Month"] = df["Date"].dt.month_name()
print(df.groupby(df["Date"].dt.month)["Sales"].sum())
df["Date"].dt.date


         Date  Sales
0  2025-01-01   4063
1  2025-02-01   3269
2  2025-03-01   5385
3  2025-04-01   7145
4  2025-05-01   9964
5  2025-06-01   7238
6  2025-07-01   9199
7  2025-08-01   3462
8  2025-09-01   4253
9  2025-10-01   5494
10 2025-11-01   4942
11 2025-12-01   4931
12 2026-01-01   3804
13 2026-02-01   9717
14 2026-03-01   9351
15 2026-04-01   5640
16 2026-05-01   3708
17 2026-06-01   5685
18 2026-07-01   8082
19 2026-08-01   6254
20 2026-09-01   9890
21 2026-10-01   9802
22 2026-11-01   8793
23 2026-12-01   4935
24 2027-01-01   4400
25 2027-02-01   7069
26 2027-03-01   9436
27 2027-04-01   7520
28 2027-05-01   8831
29 2027-06-01   6517
Date
1     12267
2     20055
3     24172
4     20305
5     22503
6     19440
7     17281
8      9716
9     14143
10    15296
11    13735
12     9866
Name: Sales, dtype: int64


,Date
0,2025-01-01
1,2025-02-01
2,2025-03-01
3,2025-04-01
4,2025-05-01
5,2025-06-01
6,2025-07-01
7,2025-08-01
8,2025-09-01
9,2025-10-01


In [ ]:
'''dates= pd.date_range(start="2024-01-01",periods= 365, freq="D")
sales= np.random.randint(1000,10000, size=365)
df= pd.DataFrame({"Date": dates, "Sales": sales})
print(df)
df["Date"]= pd.to_datetime(df["Date"])''' #2

'''dates= pd.date_range(start="2023-01-01",periods= 24, freq="MS")
sales= np.random.randint(1000,10000, size=24)
df= pd.DataFrame({"Date": dates, "Sales": sales})
print(df)
df["Date"]= pd.to_datetime(df["Date"])''' #3

dates= pd.date_range(start="2020-01-01",periods= 60, freq="MS")
sales= np.random.randint(2000,10000, size=60)
df= pd.DataFrame({"Date": dates, "Sales": sales})
print(df)
df["Date"]= pd.to_datetime(df["Date"])
df['Year']= df['Date'].dt.year
df['Month']= df['Date'].dt.month
print(df.groupby(df["Year"])["Sales"].count())
print(df.groupby(df["Month"])["Sales"].count())

         Date  Sales
0  2020-01-01   3051
1  2020-02-01   2854
2  2020-03-01   7740
3  2020-04-01   6276
4  2020-05-01   8196
5  2020-06-01   6223
6  2020-07-01   2076
7  2020-08-01   5992
8  2020-09-01   6720
9  2020-10-01   5941
10 2020-11-01   4637
11 2020-12-01   5777
12 2021-01-01   6169
13 2021-02-01   7643
14 2021-03-01   2128
15 2021-04-01   4676
16 2021-05-01   2554
17 2021-06-01   9972
18 2021-07-01   4015
19 2021-08-01   8363
20 2021-09-01   7839
21 2021-10-01   5707
22 2021-11-01   8438
23 2021-12-01   2638
24 2022-01-01   6378
25 2022-02-01   8021
26 2022-03-01   7945
27 2022-04-01   4120
28 2022-05-01   6969
29 2022-06-01   5202
30 2022-07-01   9514
31 2022-08-01   8496
32 2022-09-01   7502
33 2022-10-01   3652
34 2022-11-01   4444
35 2022-12-01   7785
36 2023-01-01   4392
37 2023-02-01   5390
38 2023-03-01   6594
39 2023-04-01   4375
40 2023-05-01   5712
41 2023-06-01   7741
42 2023-07-01   4579
43 2023-08-01   7158
44 2023-09-01   4039
45 2023-10-01   7686
46 2023-11-01

In [ ]:
import numpy as np

#print(np.__version__)
num= np.array([10,20,30,40,50])
print(num)
#arr = np.array([[10,20,30], [40,50,60]])
#print(arr)
#arr1 = np.array([[10,20,30], [40,50,60], [70,80,90]])
#print(arr1)
#arr2 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[13,14,15], [16,17,18]]])
#print(arr2)
#print(arr2.ndim)
#print(arr2.shape)
arr = np.arange(1,7) #used to generate one-dimensional arrays in a specified range
print(arr)
zeros_1d = np.zeros(5) #to create a 1Dimensional array with zeroes as values
print(zeros_1d)
zeros_2d = np.zeros((2,3)) #to create a 2Dimensional array with zeroes as values
zeros_3d = np.zeros((2,3,3)) #to create a 3Dimensional array with zeroes as values
ones_1d = np.ones(5) #to create a 1Dimensional array with ones as values, same syntax as zeroes method
'''full_1d = np.full(5,10) #to create an array with the first input value as the LENGTH and the 2nd input value as the VALUE
print(full_1d)
full_2d = np.full((2,3), 7)
full_3d = np.full((2,3,3), 7)
print(full_3d)'''
arr1 = arr.reshape(2,3) #to reshape an array into a 2d array with correct dimensions only
arr2 = arr.reshape(2,3,1) #to reshape an array into a 3d array with correct dimensions only

[10 20 30 40 50]
[1 2 3 4 5 6]
[0. 0. 0. 0. 0.]


In [ ]:
print(np.arange(10,55,5))
print(np.arange(2, 31, 2))
print(np.arange(1001,1021))
print(np.arange(50,1, -1))
roll_no = np.arange(101, 109)
#print(roll_no.shape, roll_no.ndim)
#print(roll_no.reshape(2,4))
#print(roll_no.reshape(4,2))
#print(roll_no.reshape(2,1,4))
#print(roll_no.reshape(4,1,2))


arr_2d = np.full((2,5),7)
arr_3d = np.full((2,1,5),7)
print( arr_2d,"\n", arr_3d)
print(np.zeros((3,3)))
print(np.ones((3,3)))

[10 15 20 25 30 35 40 45 50]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
[1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020]
[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2]
[[7 7 7 7 7]
 [7 7 7 7 7]] 
 [[[7 7 7 7 7]]

 [[7 7 7 7 7]]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr = np.array([10.9, 20.9, 3.0, 1],dtype = "int") #used to create an array of a specified data type that explicitly converts values into the above said  datatype
print(arr)
print(arr.dtype)

[10 20  3  1]
int64


In [ ]:
import numpy as np
arr=np.eye(3)
print(arr)
arr=np.eye(4)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
arr=np.random.random(5) #0-1 FLOAT VALUES
print(arr)
arr=np.random.random((2,3))#1D
print(arr)
arr=np.random.random((2,2,3))#2D
print(arr)
arr=np.random.uniform(10,50,5)
print(arr)
arr=np.random.uniform(10,50,(2,3))
print(arr)
arr=np.random.uniform(10,50,(2,2,3))
print(arr)
arr=np.random.randn(5)
print(arr)
print(arr.mean())
arr.std()
arr=np.random.randn(2,3)
print(arr)
print(arr.mean())
arr.std()
arr=np.random.randn(2,3,5)
print(arr)
print(arr.mean())
arr.std()
arr=np.array([10,20,30,40,50])
result=np.random.choice(arr)
print(result)
arr=np.array([10,20,30,40,50])
result=np.random.choice(arr,3)
print(result)
name=["shalu","chinnu","nirup"]
result=np.random.choice(name,2)
print(result)
arr=[10,20,30]
result=np.random.choice(arr,size=5,p=[0.2,0.5,0.3])
print(result)
arr=np.random.uniform(10,50,(2,3))  #used to freeze values
np.random.seed(10)
print(arr)
arr=np.random.random((2,3))
np.random.seed(4)
print(arr)
arr=np.random.randn(2,3)
np.random.seed(5)
print(arr)
arr=np.array([10,20,30,40,50])
np.random.shuffle(arr)
print(arr)

[0.3637369  0.979445   0.08982104 0.39673661 0.35413804]
[[0.486638   0.99082093 0.80828168]
 [0.64945888 0.81947279 0.24254041]]
[[[0.76437261 0.11090076 0.20415475]
  [0.11909536 0.87790307 0.52367529]]

 [[0.492136   0.7318711  0.01458075]
  [0.09336303 0.82655425 0.83349274]]]
[45.69644069 48.32054018 32.45348482 13.62194782 49.83955652]
[[29.0960688  37.3966243  43.73501056]
 [34.64499325 32.52750027 24.7264877 ]]
[[[37.63724789 42.64670719 47.02573955]
  [10.22940226 38.82238293 36.6823655 ]]

 [[17.99061624 37.86659718 33.0165483 ]
  [33.18885594 12.58027595 17.08984518]]]
[ 1.10626582 -1.6127783  -0.26487859 -0.21313737 -0.18430823]
-0.23376733570412603
[[ 0.42384392 -0.72306169 -0.04241936]
 [-0.90760603 -0.74412559 -0.15469471]]
-0.35801057468780945
[[[ 0.55846676 -1.52235639 -0.89264319  0.62412594 -0.80518352]
  [ 0.21228006  0.49235385  1.66745318 -1.90475993 -0.52030071]
  [-0.43239057  0.27836227  0.27090734 -0.91362123  0.35889997]]

 [[-0.53508396 -0.95499726  1.696880

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
np.random.shuffle(arr)
print(arr)
arr=np.array([10,20,30,40,50])
result=np.random.permutation(arr)
print("original:",arr)
print("permutation:",result)
arr=np.array([10,20,30,40,50])
np.random.randint(arr)
print(arr)


[40 20 30 50 10]
original: [10 20 30 40 50]
permutation: [20 10 30 40 50]
[10 20 30 40 50]


In [ ]:
import numpy as np
roll_numbers=np.array([101,102,103,104,105,106,107,108])
np.random.shuffle(roll_numbers)
print(roll_numbers)
emp=np.array(["ravi","priya","arun","kiran"])
np.random.shuffle(emp)
print(emp)
num=np.array([10,20,30,40,50])
result=np.random.permutation(num)
print("original:",num)
print("permutation:",result)
arr = np.arange(10,60,10)
print(arr)
print(np.zeros((3,3)))
print(np.zeros((2,3,4)))
print(np.ones(5))
print(np.ones((2,3)))
arr=np.eye(5)
print(arr)


[104 107 105 102 101 103 108 106]
['priya' 'ravi' 'kiran' 'arun']
original: [10 20 30 40 50]
permutation: [10 20 50 30 40]
[10 20 30 40 50]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.linspace(0,10,3)
#arr = np.linspace((1,10,3), 50)
print(arr)
arr = np.arange(1,11).reshape(2,5,1)
result = arr.ravel() #used to reshape an array into a 1D array
print(result)
#r= arr.T #used to store the Transpose of an array
#print(r)
new_arr = arr.astype(float) #used to change the data type of an array
print(new_arr)
arr = np.array([10,20,30,40,50])
print(arr[-2:]) #to index an array of 1D
print(arr[1:4]) #to slice an array of 1D
arr[4] = 100
print(arr)
arr = np.arange(1,11).reshape(2,5)
print(arr)
print(arr[1,2]) #to index an array of 2D
print(arr[0,1:4]) #to slice an array of 2D
n = np.insert(arr,3,89) #to insert a value after the specified place in an array
n1= np.insert(arr,3,[100,300]) #to insert multiple values in an array at a specified location
print(n)
new_arr= np.delete(arr,2) #to delete a value in an array at a specified location, to delete multiple values pass (arr,[location in list]) inside the delete method
print(new_arr)

[ 0.  5. 10.]
[ 1  2  3  4  5  6  7  8  9 10]
[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]
  [ 5.]]

 [[ 6.]
  [ 7.]
  [ 8.]
  [ 9.]
  [10.]]]
[40 50]
[20 30 40]
[ 10  20  30  40 100]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
8
[2 3 4]
[ 1  2  3 89  4  5  6  7  8  9 10]
[ 1  2  4  5  6  7  8  9 10]


In [ ]:
arr = np.linspace(0,100,10)
print(arr)
arr = np.linspace(1,50,15)
print(arr)
arr = np.array([10,20,30,40,50,60,70])
print(arr[0])
print(arr[-1])
print(arr[3])
#print(np.where(arr == 60)[0]) to print the location of a value in an array
print(arr[5])
arr = np.array([10,20,30,40,50,60,70,80])
print(arr[0:4])
print(arr[1:5])
print(arr[-3:])
print(arr[::2])
arr= np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[1,1], arr[0,2], arr[2,0])
print(arr[1])
print(arr[0:3,2])
print(arr[0:2])
print(arr[0:3,1:3])
print(arr[0:2,1:3])
print(arr[1:3])

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[ 1.   4.5  8.  11.5 15.  18.5 22.  25.5 29.  32.5 36.  39.5 43.  46.5
 50. ]
10
70
40
60
[10 20 30 40]
[20 30 40 50]
[60 70 80]
[10 30 50 70]
50 30 70
[40 50 60]
[30 60 90]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[20 30]
 [50 60]]
[[40 50 60]
 [70 80 90]]
